name: wordprayer
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  lucide_icons_flutter: ^3.1.20
  sqflite: ^2.3.3
  path: ^1.9.0
  intl: ^0.20.3
  path_provider: ^2.1.2
  cloud_firestore: ^6.10.0
  firebase_core: ^4.15.0
  connectivity_plus: ^7.3.1
  fl_chart: ^1.2.0
  firebase_messaging: ^16.7.0
  url_launcher: ^6.3.2
  firebase_auth: ^6.7.0
  google_sign_in: ^7.2.0
  google_fonts: ^6.2.1
  font_awesome_flutter: ^11.0.0
  fluttertoast: ^10.0.0
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1
flutter:
  uses-material-design: true

  assets:
    - assets/front_bg.webp
    - assets/back_bg.webp

# 🚀 App Icon Configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/front_bg.webp"
  adaptive_icon_background: "#001F5B"   # ✅ dark blue color
  adaptive_icon_foreground: "assets/front_bg.webp"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/front_bg.webp"
    background_color: "#001F5B"
    theme_color: "#001F5B"
