name: wordprayer
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  lucide_icons: ^0.257.0
  sqflite: ^2.3.3
  path: ^1.9.0
  intl: ^0.19.0
  path_provider: ^2.1.2
  cloud_firestore: ^5.4.0
  firebase_core: ^3.8.0
  connectivity_plus: ^6.1.0
  fl_chart: ^0.69.0
  firebase_messaging: ^15.2.10
  url_launcher: ^6.3.2
  firebase_auth: ^5.7.0
  google_sign_in: ^6.2.1
  font_awesome_flutter: ^10.5.0
  fluttertoast: ^8.2.4
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
flutter:
  uses-material-design: true

  assets:
    - assets/front_bg.webp
    - assets/back_bg.webp

# 🚀 App Icon Configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/front_bg.webp"
  adaptive_icon_background: "#001F5B"   # ✅ dark blue color
  adaptive_icon_foreground: "assets/front_bg.webp"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/front_bg.webp"
    background_color: "#001F5B"
    theme_color: "#001F5B"
