// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNX5jxGKafjtzFQCxFzIErDAEZL7rkjp4',
    appId: '1:563043534193:web:ce46635eca99a8979022d0',
    messagingSenderId: '563043534193',
    projectId: 'lively-wonder-461707-a8',
    authDomain: 'lively-wonder-461707-a8.firebaseapp.com',
    storageBucket: 'lively-wonder-461707-a8.firebasestorage.app',
    measurementId: 'G-X2WL0FQY1R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACyuay0SxeWiE2xLx0wMQCZlkP1xi9LQY',
    appId: '1:563043534193:android:29d020f11d50953a9022d0',
    messagingSenderId: '563043534193',
    projectId: 'lively-wonder-461707-a8',
    storageBucket: 'lively-wonder-461707-a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0qQJdCeRFvFoiqzu_U1bs0y2ZbbDuXtU',
    appId: '1:563043534193:ios:4459569351ca7cd59022d0',
    messagingSenderId: '563043534193',
    projectId: 'lively-wonder-461707-a8',
    storageBucket: 'lively-wonder-461707-a8.firebasestorage.app',
    iosClientId: '563043534193-213k7l4cetbnbauqdgnsete73phgvjlf.apps.googleusercontent.com',
    iosBundleId: 'com.church.wordprayer',
  );

}